// Icon mapping configuration for iKan design system
// Maps icon names and variants to both Lucide React (fallback) and Iconify icons

// Lucide React fallback mapping
export const iconMapping = {
  "home-roundedOutline": "Home",
  "home-roundedFilled": "Home", 
  "library-roundedOutline": "Library",
  "library-roundedFilled": "Library",
  "tools-roundedOutline": "Wrench",
  "tools-roundedFilled": "Wrench",
  "account-roundedOutline": "User",
  "account-roundedFilled": "User",
  "arrowRight-outline": "ArrowRight",
  "arrowRight-filled": "ArrowRight",
  "more-outline": "MoreHorizontal",
  "more-filled": "MoreHorizontal",
  "delete-outline": "Trash2",
  "delete-filled": "Trash",
  "search-outline": "Search",
  "settings-outline": "Settings",
  "settings-filled": "Settings",
  "dashboard-outline": "LayoutDashboard",
  "dashboard-filled": "LayoutDashboard",
  "assignment-outline": "FileText",
  "assignment-filled": "FileText",
  "article-outline": "FileText",
  "article-filled": "FileText",
  "info-outline": "Info",
  "info-filled": "Info",
  "checkCircle-outline": "Circle",
  "checkCircle-filled": "CheckCircle",
  "error-outline": "AlertCircle",
  "error-filled": "XCircle",
  "warning-outline": "AlertTriangle",
  "warning-filled": "AlertTriangle",
  "calendar-default": "Calendar",
  "chat-default": "MessageCircle",
  "widget-default": "Grid3X3",
  "bookmark-outline": "Bookmark",
  "bookmark-filled": "Bookmark",
  "star-outline": "Star",
  "star-filled": "Star",
  "arrowLeft-outline": "ArrowLeft",
  "wrench-outline": "Wrench",
  "wrench-roundedOutline": "Wrench",
  "clock-outline": "Clock",
  "clock-default": "Clock",
  "list-outline": "List",
  "list-default": "List",
  "play-outline": "Play",
  "play-default": "Play",
  "creditCard-outline": "CreditCard",
  "creditCard-default": "CreditCard",
  "lock-outline": "Lock",
  "lock-default": "Lock",
  "eye-outline": "Eye",
  "eye-default": "Eye",
  "clipboard-outline": "Clipboard",
  "clipboard-default": "Clipboard",
  "tag-outline": "Tag",
  "tag-default": "Tag",
  "heart-outline": "Heart",
  "heart-default": "Heart",
  "message-outline": "MessageCircle",
  "message-default": "MessageCircle"
} as const;

// Iconify mapping - using Material Symbols as specified
export const iconifyMapping = {
  "home.roundedOutline": "material-symbols:home-outline-rounded",
  "home.roundedFilled": "material-symbols:home-rounded",
  "library.roundedOutline": "material-symbols:menu-book-outline-rounded",
  "library.roundedFilled": "material-symbols:menu-book-rounded",
  "tools.roundedOutline": "material-symbols:build-outline-rounded",
  "tools.roundedFilled": "material-symbols:build-rounded",
  "account.roundedOutline": "material-symbols:person-outline-rounded",
  "account.roundedFilled": "material-symbols:person-rounded",
  "arrowRight.outline": "material-symbols:arrow-forward-ios",
  "arrowRight.filled": "material-symbols:arrow-forward-rounded",
  "more.outline": "material-symbols:more-horiz",
  "more.filled": "material-symbols:more-horiz-rounded",
  "delete.outline": "material-symbols:delete-outline-rounded",
  "delete.filled": "material-symbols:delete-rounded",
  "search.outline": "material-symbols:search",
  "settings.outline": "material-symbols:settings-outline-rounded",
  "settings.filled": "material-symbols:settings-rounded",
  "dashboard.outline": "material-symbols:dashboard-outline-rounded",
  "dashboard.filled": "material-symbols:dashboard-rounded",
  "assignment.outline": "material-symbols:assignment-outline-rounded",
  "assignment.filled": "material-symbols:assignment-rounded",
  "article.outline": "material-symbols:article-outline-rounded",
  "article.filled": "material-symbols:article-rounded",
  "info.outline": "material-symbols:info-outline-rounded",
  "info.filled": "material-symbols:info-rounded",
  "checkCircle.outline": "material-symbols:check-circle-outline-rounded",
  "checkCircle.filled": "material-symbols:check-circle-rounded",
  "error.outline": "material-symbols:error-outline-rounded",
  "error.filled": "material-symbols:error-rounded",
  "warning.outline": "material-symbols:warning-outline-rounded",
  "warning.filled": "material-symbols:warning-rounded",
  "calendar.default": "material-symbols:calendar-today-rounded",
  "chat.default": "material-symbols:chat-rounded",
  "widget.default": "material-symbols:widgets-rounded",
  "bookmark.outline": "material-symbols:bookmark-outline-rounded",
  "bookmark.filled": "material-symbols:bookmark-rounded",
  "star.outline": "material-symbols:star-outline-rounded",
  "star.filled": "material-symbols:star-rounded",
  "arrowLeft.outline": "material-symbols:arrow-back-ios",
  "wrench.outline": "material-symbols:build-outline-rounded",
  "wrench.roundedOutline": "material-symbols:build-outline-rounded",
  "clock.outline": "material-symbols:schedule-outline-rounded",
  "clock.default": "material-symbols:schedule",
  "list.outline": "material-symbols:list-outline-rounded",
  "list.default": "material-symbols:list",
  "play.outline": "material-symbols:play-arrow-outline-rounded",
  "play.default": "material-symbols:play-arrow",
  "creditCard.outline": "material-symbols:credit-card-outline-rounded",
  "creditCard.default": "material-symbols:credit-card",
  "lock.outline": "material-symbols:lock-outline-rounded",
  "lock.default": "material-symbols:lock",
  "eye.outline": "material-symbols:visibility-outline-rounded",
  "eye.default": "material-symbols:visibility",
  "clipboard.outline": "material-symbols:content-paste-outline-rounded",
  "clipboard.default": "material-symbols:content-paste",
  "tag.outline": "material-symbols:label-outline-rounded",
  "tag.default": "material-symbols:label",
  "heart.outline": "material-symbols:favorite-outline-rounded",
  "heart.default": "material-symbols:favorite",
  "message.outline": "material-symbols:chat-outline-rounded",
  "message.default": "material-symbols:chat"
} as const;

export type IconMappingKey = keyof typeof iconMapping;
export type LucideIconName = typeof iconMapping[IconMappingKey];
export type IconifyMappingKey = keyof typeof iconifyMapping;
export type IconifyIconName = typeof iconifyMapping[IconifyMappingKey];